kenclary/TNL 10332
openedx/frontend-lib-content-components pull request #200
Opened 2023-01-18 16:30 UTC by kenclary

2023-01-20 16:11 UTC, KristinAoki requested changes
When there are no hints the collapsed widget should read "None". Also `<HintRow>` should be left aligned with the header.

2023-01-20 16:11 UTC, KristinAoki commented on src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ScoringCard.jsx
>        <Form.Group>
<img width="258" alt="Screen Shot 2023-01-20 at 11 07 40 AM" src="https://user-images.githubusercontent.com/42981026/213747265-19f0937c-9e43-4148-9e65-527270543c21.png">
need to add this message here

2023-01-20 16:19 UTC, KristinAoki commented
Also can you change the title for your PR. Put all the things that you have changed in the PR description.

2023-01-20 16:59 UTC, kenclary commented on src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/HintsCard.jsx
> +        className="ml-2"
This seems reasonable, but is not covered by the jira issue. Is it accounted for somewhere else (I want to make sure I'm not doubling someone else's work)?

2023-01-20 17:01 UTC, KristinAoki commented on src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/HintsCard.jsx
> +        className="ml-2"
I didn't see it in any of the tickets that jesper is working on

2023-01-23 14:41 UTC, KristinAoki commented on src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/HintsCard.jsx
> +        className="ml-0 text-primary-500"
```suggestion
        className="pl-0 text-primary-500"
```

2023-01-23 15:31 UTC, KristinAoki commented
> When there are no hints the collapsed widget should read "None". Also `<HintRow>` should be left aligned with the header.

To fix `<HintRow>` not being left aligned, I suggest changing them component to the following:
```
  <ActionRow className="mb-4">
      <Form.Control
        value={value}
        onChange={handleChange}
        floatingLabel={intl.formatMessage(messages.hintInputLabel)}
      />
    <ActionRow.Spacer />
    <IconButton
      src={DeleteOutline}
      iconAs={Icon}
      alt={intl.formatMessage(messages.settingsDeleteIconAltText)}
      onClick={handleDelete}
    />
  </ActionRow>
```

2023-01-23 16:25 UTC, kenclary commented
Rewriting HintRow should probably be a separate PR, especially since it's not even in the original jira issue.

2023-01-23 17:06 UTC, KristinAoki approved these changes

2023-01-23 18:00 UTC, KristinAoki approved these changes

2023-01-23 18:01 UTC, merged

2023-01-27 15:08 UTC, jristau1984 commented
> Rewriting HintRow should probably be a separate PR, especially since it's not even in the original jira issue.

@kenclary just confirming - did this get a new ticket to be addressed?

2023-01-27 15:36 UTC, kenclary commented
> > Rewriting HintRow should probably be a separate PR, especially since it's not even in the original jira issue.
> 
> @kenclary just confirming - did this get a new ticket to be addressed?

I recall that @KristinAoki integrated it into a later ticket. It did not get a *new* ticket.