fix: misssing part of paid plugin configuration
openedx/frontend-lib-content-components pull request #428
Opened 2023-12-08 01:39 UTC by kenclary

fix: misssing part of paid plugin configuration

2023-12-08 20:41 UTC, KristinAoki requested changes

2023-12-08 20:41 UTC, KristinAoki commented on src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
add `buttons.a11yChecker` to quickToolbar list

2023-12-09 02:26 UTC, kenclary commented on src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
which of the regular toolbar, the quick insert toolbar, and the quick selection toolbar should it be in?

do we have any guidance about where in the toolbar(s) it should be?

2023-12-11 16:48 UTC, kenclary commented on src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
answered by Product (in slack)

2023-12-11 17:05 UTC, KristinAoki approved these changes

2023-12-11 17:07 UTC, merged