fix: block resize with long content and broken image path
openedx/frontend-lib-content-components pull request #478
Opened 2024-05-29 10:45 UTC by ihor-romaniuk

### Description
This pull request contains:
- styling fixes of Problem content editor for correct displaying with long/wide content with adding block limits and horizontal scroll
- fix broken images URL in hints and answers blocks

#### Screenshots before:
| <img width="1727" alt="image" src="https://github.com/openedx/frontend-lib-content-components/assets/17108583/59a7b1f3-c518-4fbe-b3ce-b473c133ffcb"> | <img width="1727" alt="image" src="https://github.com/openedx/frontend-lib-content-components/assets/17108583/e82a2fd8-f7ac-4058-b9ee-b5cf35c0c8c8"> |
|---|---|

#### Screenshots after:
| <img width="1727" alt="image" src="https://github.com/openedx/frontend-lib-content-components/assets/17108583/3f68b546-ceaf-4905-a744-81e9f9b97a89"> | <img width="1727" alt="image" src="https://github.com/openedx/frontend-lib-content-components/assets/17108583/a969b88b-9db6-4e1b-ab19-9ef9d0cb814c"> |
|---|---|

#### Steps to Reproduce: 
1. Enable new problem editor and sharing by adding in `/admin/waffle/flag/`
- [new_core_editors.use_new_problem_editor](http://localhost:18000/admin/waffle/flag/9/change/)
2. In studio open unit -> add new component -> Problem -> Single / Multiple select
3. Add images, table to hints and answers blocks
4. Check problem displaying

2024-05-29 10:45 UTC, openedx-webhooks commented
Thanks for the pull request, @ihor-romaniuk! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-08-16 15:22 UTC, KristinAoki requested changes

2024-08-16 15:22 UTC, KristinAoki commented on src/editors/data/redux/thunkActions/problem.js
> +    preprocessProblemData(dataFromOlx, getState());
This should be happening when the tinyMCE editor loads, so it is not necessary to preprocess the problem here. See https://github.com/openedx/frontend-lib-content-components/blob/main/src/editors/sharedComponents/TinyMceWidget/hooks.js#L74-L97

2024-08-16 15:22 UTC, KristinAoki commented on src/editors/data/redux/thunkActions/problem.js
> +    preprocessProblemData(dataFromOlx, getState());
If this is not longer needed, please remove all changes related to `preprocessProblemData`

2024-08-16 15:22 UTC, KristinAoki commented on src/editors/data/services/cms/utils.js
> +};
See comment regarding `preprocessProblemData` and remove if necessary.

2024-08-27 14:13 UTC, KristinAoki commented
Hi! Thank you for your contribution to this repo. This repo is being deprecated and all the code is being moved to `frontend-app-course-authoring`. If you would like your work to be included in the transition please resolve outstanding requests for this PR. This PR will automatically close once `frontend-app-course-authoring` PR [#1208](https://github.com/openedx/frontend-app-course-authoring/pull/1208) is merged.

2024-08-29 19:05 UTC, bradenmacdonald commented
Closing as we've now moved this code, per the notice above. Please re-open this PR against https://github.com/openedx/frontend-app-course-authoring/ if you'd like to continue it.

2024-08-29 19:05 UTC, closed without merging

2024-08-29 19:05 UTC, openedx-webhooks commented
@ihor-romaniuk Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-lib-content-components&entry.867055334=https://github.com/openedx/frontend-lib-content-components/pull/478&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2024-05-29+10:45&entry.1917517419=2024-08-29+19:05&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->